//! Scaffold `.agents/` for any repo + detect readiness (`init` / `doctor`).

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use anyhow::{bail, Context, Result};

use crate::config::{self, load_agents, resolve_lead_agent, agents_yaml_path};
use crate::lead_identity;

const COORD_TEMPLATE: &str = include_str!("../docs/COORDINATION-template.md");

const DEFAULT_AGENTS_YAML: &str = r#"# Agent registry — generated by agent-tui init
# Cwd is each agent's worktree; use agents-complete for isolated git worktrees.
agents:
  cursor:
    command: "agent"
    role: "architect"
    enabled: true
  claude:
    command: "claude"
    role: "advisor"
    enabled: true
  codex:
    command: "codex"
    role: "executor"
    enabled: true
  mimo:
    command: "mimo"
    role: "reviewer"
    enabled: true
  kimi:
    command: "kimi"
    role: "frontend"
    enabled: true
"#;

const MINIMAL_AGENTS_YAML: &str = r#"# Minimal roster — agent-tui init --minimal
agents:
  cursor:
    command: "agent"
    role: "architect"
    enabled: true
  codex:
    command: "codex"
    role: "executor"
    enabled: true
"#;

#[derive(Debug, Clone)]
pub struct ProjectStatus {
    pub project_dir: PathBuf,
    pub has_agents_yaml: bool,
    pub has_coordination: bool,
    pub agent_count: usize,
    pub lead: Option<String>,
    pub worktrees_ok: usize,
    pub worktrees_missing: Vec<String>,
    pub has_lead_rules: bool,
    pub ready_for_tui: bool,
}

pub fn detect_project(explicit: Option<PathBuf>) -> Result<ProjectStatus> {
    let project_dir = match explicit {
        Some(p) => p.canonicalize().unwrap_or(p),
        None => find_project_upward()?,
    };
    build_status(project_dir)
}

/// Like `detect_project`, but falls back to cwd when no agents.yaml (for `doctor`).
pub fn detect_project_or_cwd(explicit: Option<PathBuf>) -> ProjectStatus {
    match explicit {
        Some(p) => {
            let dir = p.canonicalize().unwrap_or(p);
            build_status(config::normalize_windows_path(dir)).unwrap_or_else(|e| fallback_cwd(e))
        }
        None => find_project_upward()
            .and_then(|d| build_status(d))
            .unwrap_or_else(|_| {
                let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
                build_status(config::normalize_windows_path(cwd)).unwrap_or_else(|e| fallback_cwd(e))
            }),
    }
}

fn fallback_cwd(_err: anyhow::Error) -> ProjectStatus {
    let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
    ProjectStatus {
        project_dir: config::normalize_windows_path(cwd),
        has_agents_yaml: false,
        has_coordination: false,
        agent_count: 0,
        lead: None,
        worktrees_ok: 0,
        worktrees_missing: Vec::new(),
        has_lead_rules: false,
        ready_for_tui: false,
    }
}

fn find_project_upward() -> Result<PathBuf> {
    let mut dir = std::env::current_dir().context("current directory")?;
    loop {
        if agents_yaml_path(&dir).is_some() {
            return Ok(config::normalize_windows_path(dir));
        }
        if !dir.pop() {
            bail!(
                "未找到 .agents/agents.yaml（从当前目录向上搜索）。\n\
                 在新项目根目录运行: agent-tui init"
            );
        }
    }
}

fn build_status(project_dir: PathBuf) -> Result<ProjectStatus> {
    let has_agents_yaml = agents_yaml_path(&project_dir).is_some();
    let coord = project_dir.join(".agents/COORDINATION.md");
    let has_coordination = coord.is_file();

    let mut agent_count = 0;
    let mut lead = None;
    let mut worktrees_ok = 0;
    let mut worktrees_missing = Vec::new();
    let mut has_lead_rules = false;

    if has_agents_yaml {
        if let Ok(agents) = load_agents(&project_dir) {
            agent_count = agents.len();
            let lead_name = resolve_lead_agent(&agents);
            lead = Some(lead_name.clone());
            for a in &agents {
                let wt = &a.worktree;
                if wt.is_dir() {
                    worktrees_ok += 1;
                } else {
                    worktrees_missing.push(a.name.clone());
                }
            }
            if let Some(spec) = agents.iter().find(|a| a.name == lead_name) {
                let rules = spec
                    .worktree
                    .join(".cursor/rules/agent-tui-orchestrator.mdc");
                has_lead_rules = rules.is_file();
            }
        }
    }

    let ready_for_tui = has_agents_yaml && agent_count > 0;

    Ok(ProjectStatus {
        project_dir,
        has_agents_yaml,
        has_coordination,
        agent_count,
        lead,
        worktrees_ok,
        worktrees_missing,
        has_lead_rules,
        ready_for_tui,
    })
}

pub fn format_doctor_report(status: &ProjectStatus) -> String {
    let mut out = String::new();
    out.push_str(&format!("项目: {}\n", status.project_dir.display()));
    out.push_str(&format!(
        "agents.yaml: {}\n",
        if status.has_agents_yaml { "✓" } else { "✗ 缺失" }
    ));
    out.push_str(&format!(
        "COORDINATION.md: {}\n",
        if status.has_coordination {
            "✓"
        } else {
            "○ 建议添加"
        }
    ));
    if status.has_agents_yaml {
        out.push_str(&format!("Agent 数量: {}\n", status.agent_count));
        if let Some(ref lead) = status.lead {
            out.push_str(&format!("Lead: {lead}\n"));
        }
        out.push_str(&format!(
            "worktree 就绪: {}/{}",
            status.worktrees_ok,
            status.worktrees_ok + status.worktrees_missing.len()
        ));
        if !status.worktrees_missing.is_empty() {
            out.push_str(&format!(
                "（缺失: {} — TUI 会回退到项目根 cwd）\n",
                status.worktrees_missing.join(", ")
            ));
        } else {
            out.push('\n');
        }
        out.push_str(&format!(
            "Lead orchestrator 规则: {}\n",
            if status.has_lead_rules {
                "✓"
            } else {
                "✗ 运行 agent-tui sync-lead"
            }
        ));
    }
    out.push_str(&format!(
        "\nTUI 就绪: {}\n",
        if status.ready_for_tui { "是" } else { "否 — 先 agent-tui init" }
    ));
    if status.ready_for_tui {
        out.push_str(&format!(
            "\n启动: agent-tui --project-dir {}\n",
            status.project_dir.display()
        ));
    } else {
        out.push_str("\n初始化: agent-tui init\n");
    }
    out
}

pub struct InitOptions {
    pub force: bool,
    pub link_worktrees: bool,
    pub sync_lead: bool,
    pub minimal: bool,
}

pub struct InitOutcome {
    pub project_dir: PathBuf,
    pub created_agents_yaml: bool,
    pub created_coordination: bool,
    pub linked_worktrees: Vec<String>,
    pub synced_lead: bool,
}

pub fn init_project(project_dir: &Path, opts: &InitOptions) -> Result<InitOutcome> {
    let project_dir = project_dir
        .canonicalize()
        .unwrap_or_else(|_| project_dir.to_path_buf());
    let project_dir = config::normalize_windows_path(project_dir);

    let agents_dir = project_dir.join(".agents");
    fs::create_dir_all(agents_dir.join("shared"))
        .with_context(|| format!("mkdir {}", agents_dir.display()))?;

    let yaml_path = agents_dir.join("agents.yaml");
    let mut created_agents_yaml = false;
    if yaml_path.is_file() && !opts.force {
        // keep existing
    } else {
        let body = if opts.minimal {
            MINIMAL_AGENTS_YAML
        } else {
            DEFAULT_AGENTS_YAML
        };
        fs::write(&yaml_path, body).with_context(|| format!("write {}", yaml_path.display()))?;
        created_agents_yaml = true;
    }

    let coord_path = agents_dir.join("COORDINATION.md");
    let mut created_coordination = false;
    if !coord_path.is_file() || opts.force {
        fs::write(&coord_path, COORD_TEMPLATE)
            .with_context(|| format!("write {}", coord_path.display()))?;
        created_coordination = true;
    }

    seed_shared_files(&agents_dir)?;

    let agents = load_agents(&project_dir)?;
    let mut linked_worktrees = Vec::new();
    for a in &agents {
        ensure_agent_memory(&project_dir, &a.name)?;
        if opts.link_worktrees {
            if try_link_worktree(&a.worktree, &project_dir)? {
                linked_worktrees.push(a.name.clone());
            }
        }
    }

    let mut synced_lead = false;
    if opts.sync_lead {
        let lead = resolve_lead_agent(&agents);
        if let Some(spec) = agents.iter().find(|a| a.name == lead) {
            if opts.link_worktrees && !spec.worktree.is_dir() {
                let _ = try_link_worktree(&spec.worktree, &project_dir);
            } else if !spec.worktree.is_dir() {
                fs::create_dir_all(&spec.worktree)?;
            }
            lead_identity::sync_lead_context(&project_dir, &lead, &spec.worktree)?;
            let _ = crate::agent_memory::refresh_lead_identity(&project_dir, &lead);
            synced_lead = true;
        }
    }

    Ok(InitOutcome {
        project_dir,
        created_agents_yaml,
        created_coordination,
        linked_worktrees,
        synced_lead,
    })
}

fn seed_shared_files(agents_dir: &Path) -> Result<()> {
    let shared = agents_dir.join("shared");
    let inbox = shared.join("inbox.md");
    if !inbox.is_file() {
        fs::write(
            &inbox,
            "# 留言板\n\n使用 TUI `!任务 …` 或 `agent-tui notify` 提交。\n",
        )?;
    }
    for name in ["mailbox.jsonl", "events.jsonl", "task_state.jsonl"] {
        let p = shared.join(name);
        if !p.exists() {
            let _ = fs::OpenOptions::new().create(true).write(true).open(&p)?;
        }
    }
    Ok(())
}

fn ensure_agent_memory(project_dir: &Path, agent: &str) -> Result<()> {
    let dir = project_dir.join(format!(".agents/{agent}/memory"));
    fs::create_dir_all(&dir).with_context(|| format!("mkdir {}", dir.display()))?;
    Ok(())
}

/// Junction/symlink worktree → project root (single-repo mode). Returns true if linked.
fn try_link_worktree(worktree: &Path, project: &Path) -> Result<bool> {
    if worktree.is_dir() {
        return Ok(false);
    }
    if let Some(parent) = worktree.parent() {
        fs::create_dir_all(parent)?;
    }
    #[cfg(windows)]
    {
        let wt = worktree.to_string_lossy();
        let proj = project.to_string_lossy();
        let status = Command::new("cmd")
            .args(["/C", "mklink", "/J", wt.as_ref(), proj.as_ref()])
            .status()
            .context("mklink /J")?;
        return Ok(status.success());
    }
    #[cfg(not(windows))]
    {
        std::os::unix::fs::symlink(project, worktree)
            .with_context(|| format!("symlink {} -> {}", worktree.display(), project.display()))?;
        Ok(true)
    }
}

pub fn format_init_summary(outcome: &InitOutcome) -> String {
    let mut s = format!(
        "已初始化 agent-tui → {}\n",
        outcome.project_dir.display()
    );
    if outcome.created_agents_yaml {
        s.push_str("  + agents.yaml\n");
    } else {
        s.push_str("  · agents.yaml（保留已有）\n");
    }
    if outcome.created_coordination {
        s.push_str("  + COORDINATION.md\n");
    }
    if !outcome.linked_worktrees.is_empty() {
        s.push_str(&format!(
            "  + worktree 联接（单仓模式）: {}\n",
            outcome.linked_worktrees.join(", ")
        ));
    }
    if outcome.synced_lead {
        s.push_str("  + sync-lead（orchestrator.mdc + LEAD.md）\n");
    }
    s.push_str(&format!(
        "\n下一步:\n  agent-tui --project-dir {}\n  agent-tui doctor\n",
        outcome.project_dir.display()
    ));
    s
}

/// Headless: init minimal project in temp dir.
pub fn verify_init_scaffold() -> Result<()> {
    let dir = std::env::temp_dir().join(format!("agent-init-verify-{}", std::process::id()));
    let _ = std::fs::remove_dir_all(&dir);
    std::fs::create_dir_all(&dir)?;
    let outcome = init_project(
        &dir,
        &InitOptions {
            force: true,
            link_worktrees: false,
            sync_lead: true,
            minimal: true,
        },
    )?;
    if !outcome.project_dir.join(".agents/agents.yaml").is_file() {
        bail!("init verify: agents.yaml missing");
    }
    let status = build_status(dir.clone())?;
    if !status.ready_for_tui {
        bail!("init verify: not ready for tui");
    }
    let _ = std::fs::remove_dir_all(&dir);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::env;

    #[test]
    fn init_scaffold_in_temp() {
        let dir = env::temp_dir().join(format!("agent-init-{}", std::process::id()));
        let _ = fs::remove_dir_all(&dir);
        fs::create_dir_all(&dir).unwrap();
        let outcome = init_project(
            &dir,
            &InitOptions {
                force: true,
                link_worktrees: false,
                sync_lead: true,
                minimal: true,
            },
        )
        .expect("init");
        assert!(outcome.project_dir.join(".agents/agents.yaml").is_file());
        assert!(agents_yaml_path(&dir).is_some());
        let status = build_status(dir.clone()).unwrap();
        assert!(status.ready_for_tui);
        let _ = fs::remove_dir_all(&dir);
    }
}
